import Link from "next/link";
import { Button } from "@/components/ui/button";

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-gradient-to-b from-slate-50 to-white">
      {/* Navigation */}
      <header className="fixed top-0 left-0 right-0 z-50 bg-white/80 backdrop-blur-md border-b border-slate-200">
        <nav className="container mx-auto px-4 py-4 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2">
            <div className="w-8 h-8 bg-blue-600 rounded-lg flex items-center justify-center">
              <span className="text-white font-bold text-lg">A</span>
            </div>
            <span className="font-bold text-xl text-slate-900">AutoGradeX</span>
          </Link>
          
          <div className="flex items-center gap-4">
            <Link href="/signin">
              <Button variant="ghost" className="hidden sm:inline-flex">
                Sign In
              </Button>
            </Link>
            <Link href="/signup">
              <Button className="bg-blue-600 hover:bg-blue-700">
                Get Started Free
              </Button>
            </Link>
          </div>
        </nav>
      </header>

      {/* Content */}
      <section className="pt-32 pb-20 px-4">
        <div className="container mx-auto max-w-4xl">
          <h1 className="text-4xl md:text-5xl font-bold text-slate-900 mb-6">
            Privacy Policy
          </h1>
          <p className="text-slate-500 mb-12">Last updated: January 28, 2026</p>
          
          <div className="prose prose-lg prose-slate max-w-none">
            <h2 className="text-2xl font-bold text-slate-900 mt-8 mb-4">1. Introduction</h2>
            <p className="text-slate-600 mb-6">
              AutoGradeX (&quot;we,&quot; &quot;our,&quot; or &quot;us&quot;) is committed to protecting your privacy. 
              This Privacy Policy explains how we collect, use, disclose, and safeguard your 
              information when you use our AI-powered grading platform.
            </p>

            <h2 className="text-2xl font-bold text-slate-900 mt-8 mb-4">2. Information We Collect</h2>
            <h3 className="text-xl font-semibold text-slate-800 mt-6 mb-3">Personal Information</h3>
            <p className="text-slate-600 mb-4">We may collect personal information that you provide directly to us, including:</p>
            <ul className="list-disc list-inside text-slate-600 mb-6 space-y-2">
              <li>Name and email address when you create an account</li>
              <li>Educational institution affiliation</li>
              <li>Payment information for premium subscriptions</li>
              <li>Profile information you choose to provide</li>
            </ul>

            <h3 className="text-xl font-semibold text-slate-800 mt-6 mb-3">Educational Data</h3>
            <p className="text-slate-600 mb-4">As an educational technology provider, we process:</p>
            <ul className="list-disc list-inside text-slate-600 mb-6 space-y-2">
              <li>Assignment submissions and content</li>
              <li>Grades and feedback generated by our AI</li>
              <li>Course and assignment information</li>
              <li>Student performance data</li>
            </ul>

            <h2 className="text-2xl font-bold text-slate-900 mt-8 mb-4">3. How We Use Your Information</h2>
            <p className="text-slate-600 mb-4">We use the information we collect to:</p>
            <ul className="list-disc list-inside text-slate-600 mb-6 space-y-2">
              <li>Provide, maintain, and improve our services</li>
              <li>Process assignments and generate AI-powered grades and feedback</li>
              <li>Communicate with you about your account and our services</li>
              <li>Ensure the security and integrity of our platform</li>
              <li>Comply with legal obligations</li>
            </ul>

            <h2 className="text-2xl font-bold text-slate-900 mt-8 mb-4">4. FERPA Compliance</h2>
            <p className="text-slate-600 mb-6">
              AutoGradeX is committed to compliance with the Family Educational Rights and Privacy 
              Act (FERPA). We act as a &quot;school official&quot; under FERPA and only use educational 
              records for the purposes specified by educational institutions. We do not use 
              student data for advertising or sell student information to third parties.
            </p>

            <h2 className="text-2xl font-bold text-slate-900 mt-8 mb-4">5. Data Security</h2>
            <p className="text-slate-600 mb-6">
              We implement industry-standard security measures to protect your data, including 
              encryption in transit and at rest, regular security audits, and access controls. 
              However, no method of transmission over the Internet is 100% secure, and we cannot 
              guarantee absolute security.
            </p>

            <h2 className="text-2xl font-bold text-slate-900 mt-8 mb-4">6. Data Retention</h2>
            <p className="text-slate-600 mb-6">
              We retain your data for as long as your account is active or as needed to provide 
              services. Educational institutions may request deletion of their data at any time. 
              We may retain certain information as required by law or for legitimate business purposes.
            </p>

            <h2 className="text-2xl font-bold text-slate-900 mt-8 mb-4">7. Your Rights</h2>
            <p className="text-slate-600 mb-4">Depending on your location, you may have the right to:</p>
            <ul className="list-disc list-inside text-slate-600 mb-6 space-y-2">
              <li>Access, correct, or delete your personal information</li>
              <li>Object to or restrict processing of your data</li>
              <li>Request data portability</li>
              <li>Withdraw consent where applicable</li>
            </ul>

            <h2 className="text-2xl font-bold text-slate-900 mt-8 mb-4">8. Contact Us</h2>
            <p className="text-slate-600 mb-6">
              If you have questions about this Privacy Policy or our privacy practices, please 
              contact us at:
            </p>
            <p className="text-slate-600 mb-6">
              <strong>Email:</strong> privacy@autogradex.com<br />
              <strong>Address:</strong> AutoGradeX Inc., 123 Education Lane, San Francisco, CA 94102
            </p>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="py-8 px-4 bg-slate-900">
        <div className="container mx-auto max-w-6xl text-center text-slate-400 text-sm">
          <p>© {new Date().getFullYear()} AutoGradeX. All rights reserved.</p>
          <div className="flex justify-center gap-6 mt-4">
            <Link href="/about" className="hover:text-white transition-colors">About</Link>
            <Link href="/terms" className="hover:text-white transition-colors">Terms</Link>
            <Link href="/contact" className="hover:text-white transition-colors">Contact</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
